src/Entity/Etape.php
<?php

namespace App\Entity;

use App\Repository\EtapeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EtapeRepository::class)
 */
class Etape
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $depart;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $arrival;

    /**
     * @ORM\Column(type="datetime")
     */
    private $depart_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $arrival_date;

    /**
     * @ORM\Column(type="string", length=4, nullable=true)
     */
    private $seat;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $gate;

    /**
     * @ORM\ManyToOne(targetEntity=Voyages::class, inversedBy="etapes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $voyage;

    /**
     * @ORM\OneToOne(targetEntity=Transport::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $transport;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDepart(): ?string
    {
        return $this->depart;
    }

    public function setDepart(string $depart): self
    {
        $this->depart = $depart;

        return $this;
    }

    public function getArrival(): ?string
    {
        return $this->arrival;
    }

    public function setArrival(string $arrival): self
    {
        $this->arrival = $arrival;

        return $this;
    }

    public function getDepartDate(): ?\DateTimeInterface
    {
        return $this->depart_date;
    }

    public function setDepartDate(\DateTimeInterface $depart_date): self
    {
        $this->depart_date = $depart_date;

        return $this;
    }

    public function getArrivalDate(): ?\DateTimeInterface
    {
        return $this->arrival_date;
    }

    public function setArrivalDate(\DateTimeInterface $arrival_date): self
    {
        $this->arrival_date = $arrival_date;

        return $this;
    }

    public function getSeat(): ?string
    {
        return $this->seat;
    }

    public function setSeat(?string $seat): self
    {
        $this->seat = $seat;

        return $this;
    }

    public function getGate(): ?string
    {
        return $this->gate;
    }

    public function setGate(?string $gate): self
    {
        $this->gate = $gate;

        return $this;
    }

    public function getVoyage(): ?Voyages
    {
        return $this->voyage;
    }

    public function setVoyage(?Voyages $voyage): self
    {
        $this->voyage = $voyage;

        return $this;
    }

    public function getTransport(): ?Transport
    {
        return $this->transport;
    }

    public function setTransport(Transport $transport): self
    {
        $this->transport = $transport;

        return $this;
    }
}

src/Entity/Transport.php
<?php

namespace App\Entity;

use App\Repository\TransportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TransportRepository::class)
 */
class Transport
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $number;

    /**
     * @ORM\ManyToOne(targetEntity=TypeTransport::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $type_transport;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getTypeTransport(): ?TypeTransport
    {
        return $this->type_transport;
    }

    public function setTypeTransport(?TypeTransport $type_transport): self
    {
        $this->type_transport = $type_transport;

        return $this;
    }
}

src/Entity/Voyages.php
<?php

namespace App\Entity;

use App\Repository\VoyagesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VoyagesRepository::class)
 */
class Voyages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\OneToMany(targetEntity=Etape::class, mappedBy="voyage", orphanRemoval=true)
     */
    private $etapes;

    public function __construct()
    {
        $this->etapes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * @return Collection<int, Etape>
     */
    public function getEtapes(): Collection
    {
        return $this->etapes;
    }

    public function addEtape(Etape $etape): self
    {
        if (!$this->etapes->contains($etape)) {
            $this->etapes[] = $etape;
            $etape->setVoyage($this);
        }

        return $this;
    }

    public function removeEtape(Etape $etape): self
    {
        if ($this->etapes->removeElement($etape)) {
            // set the owning side to null (unless already changed)
            if ($etape->getVoyage() === $this) {
                $etape->setVoyage(null);
            }
        }

        return $this;
    }
}

src/Form/VoyagesType.php
<?php

namespace App\Form;

use App\Entity\Voyages;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VoyagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Voyages::class,
        ]);
    }
}

src/Controller/VoyagesController.php
<?php

namespace App\Controller;

use App\Entity\Voyages;
use App\Form\VoyagesType;
use App\Repository\VoyagesRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class VoyagesController extends AbstractController
{
    /**
     * @Route("/", name="app_voyages_index", methods={"GET"})
     */
    public function index(ManagerRegistry $entityManager): Response
    {
        $voyages = $entityManager
            ->getRepository(Voyages::class)
            ->findAll();

        return $this->render('voyages/index.html.twig', [
            'voyages' => $voyages,
        ]);
    }

    /**
     * @Route("/new", name="app_voyages_new", methods={"GET", "POST"})
     */
    public function new(Request $request): Response
    {
        $voyage = new Voyages();
        $form = $this->createForm(VoyagesType::class, $voyage);
        $form->handleRequest($request);
        $ent = $this->getDoctrine()->getManager();

        if ($form->isSubmitted() && $form->isValid()) {
           // dd($ent);
            $ent->persist($voyage);
            $ent->flush();

            return $this->redirectToRoute('app_voyages_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('voyages/new.html.twig', [
            'voyage' => $voyage,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/show/{id}", name="app_voyages_show", methods={"GET"})
     */
    public function show(Voyages $voyage): Response
    {
        return $this->render('voyages/show.html.twig', [
            'voyage' => $voyage,
        ]);
    }

    /**
     * @Route("/edit/{id}", name="app_voyages_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Voyages $voyage): Response
    {
        $form = $this->createForm(VoyagesType::class, $voyage);
        $form->handleRequest($request);
        $entityManager = $this->getDoctrine()->getManager();

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_voyages_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('voyages/edit.html.twig', [
            'voyage' => $voyage,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/delete/{id}", name="app_voyages_delete", methods={"POST"})
     */
    public function delete(Request $request, Voyages $voyage, ManagerRegistry $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$voyage->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($voyage);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_voyages_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/voyages/_delete_form.html.twig
<form method="post" action="{{ path('app_voyages_delete', {'id': voyage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ voyage.id) }}">
    <button class="btn">Delete</button>
</form>

templates/voyages/_etapes.html.twig
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Transport Type</th>
                <th>Transport Number</th>
                <th>Depart</th>
                <th>Arrival</th>
                <th>Depart_date</th>
                <th>Arrival_date</th>
                <th>Seat</th>
                <th>Gate</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for etape in etapes %}
            <tr>
                <td>{{ etape.id }}</td>
                <td>{{ etape.transport.typeTransport.libelle }}</td>
                <td>{{ etape.transport.number }}</td>
                <td>{{ etape.depart }}</td>
                <td>{{ etape.arrival }}</td>
                <td>{{ etape.departDate ? etape.departDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ etape.arrivalDate ? etape.arrivalDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ etape.seat }}</td>
                <td>{{ etape.gate }}</td>
                <td>
                    <a class="btn btn-danger" href="{{ path('app_etape_show', {'id': etape.id}) }}">show</a>
                    <a class="btn btn-danger" href="{{ path('app_etape_edit', {'id': etape.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

   <!-- <a href="{{ path('app_etape_new') }}">add new step</a>-->
   <a class="btn btn-success" href="{{ path('add_etape', {'id': voyage.id}) }}">add a new stage</a>

templates/voyages/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/voyages/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Voyages{% endblock %}

{% block body %}
    <h1>Edit Voyages</h1>

    {{ include('voyages/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_voyages_index') }}">back to list</a>

    {{ include('voyages/_delete_form.html.twig') }}
{% endblock %}

templates/voyages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voyages index{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center">Voyages</h1>
        {% for voyage in voyages %}
        <div>
            <div class="row mt-5">
                <div class="col-md-4">
                <h2>{{ voyage.libelle }} --{{ voyage.id }}</h2>
                </div>
                <div class="col-md-8 text-start">
                <a class="btn btn-danger" href="{{ path('app_voyages_show', {'id': voyage.id}) }}">show</a>
                <a class="btn btn-danger" href="{{ path('app_voyages_edit', {'id': voyage.id}) }}">edit</a>
               <!-- <a href="{{ path('add_etape', {'id': voyage.id}) }}">add Step</a>-->
                <a class="btn btn-success " href="{{ path('app_voyages_new') }}">Add new trip</a>
                </div>
            </div>
            <div>
                {{ include('voyages/_etapes.html.twig', {'etapes': voyage.getEtapes()}) }}
            </div>
        </div>
        {% endfor %}
            </div>
        </div>
        <a class="btn btn-primary mt-3" href="{{ path('app_voyages_new') }}">Add new trip</a>
    </div>
    
{% endblock %}

templates/voyages/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Voyages{% endblock %}

{% block body %}
    <h1>Create new Voyages</h1>

    {{ include('voyages/_form.html.twig') }}

    <a href="{{ path('app_voyages_index') }}">back to list</a>
{% endblock %}

templates/voyages/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voyages{% endblock %}

{% block body %}
    <h1>Voyages</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ voyage.id }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ voyage.libelle }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_voyages_index') }}">back to list</a>

    <a href="{{ path('app_voyages_edit', {'id': voyage.id}) }}">edit</a>

    {{ include('voyages/_delete_form.html.twig') }}
{% endblock %}